### ISSUE TITLE
课表的html代码去哪弄呀

### ISSUE THREAD

**Issue by InTheClodus** [lml256/course-table#1]

**Comment by lml256** [comment]
课表的HTML代码是指强智教务系统学期理论课表页面的HTML代码。

你可以先进入学期理论课表页面，右键选择**查看网页源代码**选项获取源代码。

该仓库长时间未维护，鉴于强制教务系统升级的原因，实际的解析效果可能会有出入。强烈建议使用文档中的接口来获取课表信息。
